// Copyright 2019-2020 the donut authors. See AUTHORS.md

#pragma once

#include <string>

namespace Donut
{
class GameCommands
{
public:
	GameCommands() = delete;
	~GameCommands() = delete;

	static void HelloWorld();
	static void LoadP3DFile(const std::string&, const std::string& = "");
	static void SetParticleTexture(int32_t, const std::string&);
	static void BindReward(const std::string&, const std::string&, const std::string&, const std::string&, int32_t, int32_t = 0,
	                       const std::string& = "");
	static void SetCarAttributes(const std::string&, float, float, float, float);
	static void SetTotalGags(int32_t, int32_t);
	static void SelectMission(const std::string&);
	static void SetMissionResetPlayerInCar(const std::string&);
	static void SetDynaLoadData(const std::string&, const std::string& = "");
	static void UsePedGroup(int32_t);
	static void AddStage(const std::string& = "", const std::string& = "", const std::string& = "");
	static void SetPresentationBitmap(const std::string&);
	static void SetStageMessageIndex(int32_t, const std::string& = "");
	static void AddObjective(const std::string&, const std::string& = "", const std::string& = "");
	static void SetObjTargetVehicle(const std::string&);
	static void CloseObjective(int32_t = 0);
	static void CloseStage(int32_t = 0);
	static void RESET_TO_HERE(int32_t = 0);
	static void SetHUDIcon(const std::string&);
	static void AddCollectible(const std::string&, const std::string& = "", const std::string& = "", const std::string& = "");
	static void SetStageTime(int32_t);
	static void AddCondition(const std::string&, const std::string& = "");
	static void CloseCondition(int32_t = 0);
	static void ShowStageComplete(int32_t = 0);
	static void AddNPC(const std::string&, const std::string&, const std::string& = "");
	static void SetDestination(const std::string&, const std::string& = "");
	static void SetCollectibleEffect(const std::string&);
	static void AddStageTime(int32_t);
	static void AddObjectiveNPCWaypoint(const std::string&, const std::string&);
	static void SetTalkToTarget(const std::string&, int32_t = 0, float = 0.0f, const std::string& = "");
	static void SetDialogueInfo(const std::string&, const std::string&, const std::string&, int32_t);
	static void SetCamBestSide(const std::string&, const std::string& = "");
	static void CloseMission(int32_t = 0);
	static void PlacePlayerCar(const std::string&, const std::string&);
	static void SetMaxTraffic(int32_t);
	static void AddStageVehicle(const std::string&, const std::string&, const std::string&, const std::string&,
	                            const std::string& = "");
	static void AddStageWaypoint(const std::string&);
	static void SetRaceLaps(int32_t);
	static void SetDemoLoopTime(int64_t);
	static void AddStageMusicChange(int32_t = 0);
	static void LoadDisposableCar(const std::string&, const std::string&, const std::string&);
	static void AddMission(const std::string&);
	static void ClearGagBindings(int32_t = 0);
	static void GagBegin(const std::string&);
	static void GagSetInterior(const std::string&);
	static void GagSetCycle(const std::string&);
	static void GagSetPosition(const std::string&);
	static void GagSetPosition(float, float, float);
	static void GagSetRandom(int32_t);
	static void GagSetSound(const std::string&);
	static void GagSetTrigger(const std::string&, const std::string&, float);
	static void GagSetTrigger(const std::string&, float, float, float, float);
	static void GagEnd(int32_t = 0);
	static void GagSetSparkle(int32_t);
	static void GagSetPersist(int32_t);
	static void GagSetCoins(int32_t, float);
	static void GagSetAnimCollision(int32_t);
	static void GagSetIntro(int32_t);
	static void GagSetOutro(int32_t);
	static void GagSetCameraShake(float, int32_t, float);
	static void GagPlayFMV(const std::string&);
	static void EnableTutorialMode(const std::string&);
	static void InitLevelPlayerVehicle(const std::string&, const std::string&, const std::string&, const std::string& = "");
	static void AddCharacter(const std::string&, const std::string&);
	static void CreateChaseManager(const std::string&, const std::string&, int32_t);
	static void SetHitAndRunDecay(float);
	static void SetNumChaseCars(const std::string&);
	static void AddNPCCharacterBonusMission(const std::string&, const std::string&, const std::string&, const std::string&,
	                                        const std::string&, const std::string&, int32_t, const std::string& = "");
	static void AddBonusMissionNPCWaypoint(const std::string&, const std::string&);
	static void AddAmbientCharacter(const std::string&, const std::string&, float);
	static void AddAmbientNPCWaypoint(const std::string&, const std::string&);
	static void AddPurchaseCarReward(const std::string&, const std::string&, const std::string&, const std::string&, float,
	                                 const std::string&);
	static void AddPurchaseCarNPCWaypoint(const std::string&, const std::string&);
	static void CreateTrafficGroup(int32_t);
	static void AddTrafficModel(const std::string&, int32_t, int32_t = 0);
	static void CloseTrafficGroup(int32_t = 0);
	static void CreatePedGroup(int32_t);
	static void AddPed(const std::string&, int32_t);
	static void ClosePedGroup(int32_t = 0);
	static void PreallocateActors(const std::string&, const std::string&);
	static void SetProjectileStats(const std::string&, const std::string&, const std::string&);
	static void AddSpawnPointByLocatorScript(const std::string&, const std::string&, const std::string&, const std::string&,
	                                         const std::string&, const std::string&);
	static void AddBehaviour(const std::string&, const std::string&, const std::string&, const std::string& = "",
	                         const std::string& = "", const std::string& = "", const std::string& = "");
	static void SetActorRotationSpeed(const std::string&, const std::string&);
	static void SetAnimatedCameraName(const std::string&);
	static void SetAnimCamMulticontName(const std::string&);
	static void SetCoinFee(int32_t);
	static void PutMFPlayerInCar(int32_t = 0);
	static void StartCountdown(const std::string&, const std::string& = "");
	static void AddToCountdownSequence(const std::string&, int32_t);
	static void UseElapsedTime(int32_t = 0);
	static void SetRaceEnteryFee(int32_t);
	static void SetParTime(int32_t);
	static void SetCondMinHealth(float);
	static void SetCondTargetVehicle(const std::string&);
	static void SetCondTime(int32_t);
	static void AddBonusMission(const std::string&);
	static void AddTeleportDest(const std::string&, float, float, float, const std::string&);
	static void AddVehicleSelectInfo(const std::string&, const std::string&, const std::string&);
	static void SuppressDriver(const std::string&);
	static void SetBonusMissionDialoguePos(const std::string&, const std::string&, const std::string&, const std::string&);
	static void SetConversationCam(int32_t, const std::string&, const std::string& = "");
	static void ClearAmbientAnimations(const std::string&);
	static void AddAmbientNpcAnimation(const std::string&, const std::string& = "");
	static void AddAmbientPcAnimation(const std::string&, const std::string& = "");
	static void SetCoinDrawable(const std::string&);
	static void AmbientAnimationRandomize(int32_t, int32_t);
	static void TurnGotoDialogOff(int32_t = 0);
	static void SetCompletionDialog(const std::string&, const std::string& = "");
	static void SetMissionResetPlayerOutCar(const std::string&, const std::string&);
	static void SetMissionStartCameraName(const std::string&);
	static void SetMissionStartMulticontName(const std::string&);
	static void SetInitialWalk(const std::string&);
	static void SetDialoguePositions(const std::string&, const std::string&, const std::string&, int32_t = 0);
	static void ActivateVehicle(const std::string&, const std::string&, const std::string&);
	static void SetStageMusicAlwaysOn(int32_t = 0);
	static void SetNumValidFailureHints(int32_t);
	static void SetVehicleAIParams(const std::string&, int32_t, int32_t);
	static void StageStartMusicEvent(const std::string&);
	static void AllowMissionAbort(const std::string&);
	static void MustActionTrigger(int32_t = 0);
	static void SetStageAITargetCatchupParams(const std::string&, int32_t, int32_t);
	static void SetFollowDistances(int32_t, int32_t);
	static void SetFadeOut(float);
	static void StayInBlack(int32_t = 0);
	static void AddStageCharacter(const std::string&, const std::string&, const std::string&, const std::string&,
	                              const std::string&);
	static void SetDurationTime(float);
	static void SetFMVInfo(const std::string&, const std::string& = "");
	static void SetForcedCar(int32_t = 0);
	static void SwapInDefaultCar(int32_t = 0);
	static void SetSwapDefaultCarLocator(const std::string&);
	static void SetSwapForcedCarLocator(const std::string&);
	static void SetSwapPlayerLocator(const std::string&);
	static void StreetRacePropsLoad(const std::string&);
	static void StreetRacePropsUnload(const std::string&);
	static void SetStageAIRaceCatchupParams(const std::string&, int32_t, float, float, float);
	static void DisableHitAndRun(int32_t = 0);
	static void NoTrafficForStage(int32_t = 0);
	static void SetConditionPosition(int32_t);
	static void AddSafeZone(const std::string&, int32_t);
	static void AddGagBinding(const std::string&, const std::string&, const std::string&, int32_t, const std::string&);
	static void SetPostLevelFMV(const std::string&);
	static void SetHitNRun(int32_t = 0);
	static void SetObjDistance(int32_t);
	static void SetMusicState(const std::string&, const std::string&);
	static void SetIrisWipe(float);
	static void RemoveDriver(const std::string&);
	static void RemoveNPC(const std::string&);
	static void AddDriver(const std::string&, const std::string&);
	static void SetCharacterToHide(const std::string&);
	static void SetLevelOver(int32_t = 0);
	static void GagCheckCollCards(const std::string&, const std::string&, const std::string&, const std::string&,
	                              const std::string&);
	static void GagCheckMovie(const std::string&, const std::string&, const std::string&, const std::string&);
	static void GagSetSoundLoadDistances(int32_t, int32_t);
	static void BindCollectibleTo(int32_t, int32_t);
	static void AddShield(const std::string&, const std::string&);
	static void SetStatepropShadow(const std::string&, const std::string&);
	static void AddFlyingActorByLocator(const std::string&, const std::string&, const std::string&, const std::string&);
	static void AddCollectibleStateProp(const std::string&, const std::string&, int32_t);
	static void SetPickupTarget(const std::string&);
	static void SetObjTargetBoss(const std::string&);
	static void AllowRockOut(int32_t = 0);
	static void ShowHUD(const std::string&);
	static void SetGameOver(int32_t = 0);
	static void GoToPsScreenWhenDone(int32_t = 0);
	static void SetMass(float);
	static void SetGasScale(float);
	static void SetSlipGasScale(float);
	static void SetBrakeScale(float);
	static void SetTopSpeedKmh(float);
	static void SetMaxWheelTurnAngle(float);
	static void SetHighSpeedSteeringDrop(float);
	static void SetTireGrip(float);
	static void SetNormalSteering(float);
	static void SetSlipSteering(float);
	static void SetEBrakeEffect(float);
	static void SetSlipSteeringNoEBrake(float);
	static void SetSlipEffectNoEBrake(float);
	static void SetCMOffsetX(float);
	static void SetCMOffsetY(float);
	static void SetCMOffsetZ(float);
	static void SetSuspensionLimit(float);
	static void SetSpringK(float);
	static void SetDamperC(float);
	static void SetSuspensionYOffset(float);
	static void SetHitPoints(float);
	static void SetBurnoutRange(float);
	static void SetMaxSpeedBurstTime(float);
	static void SetDonutTorque(float);
	static void SetWeebleOffset(float);
	static void SetWheelieRange(float);
	static void SetWheelieOffsetY(float);
	static void SetWheelieOffsetZ(float);
	static void SetShadowAdjustments(float, float, float, float, float, float, float, float);
	static void SetCharactersVisible(int32_t);
	static void SetIrisTransition(int32_t);
	static void SetCharacterScale(float);
	static void SetGamblingOdds(float);
	static void SetDriver(const std::string&);
	static void SetHasDoors(int32_t);
	static void SetShininess(float);
	static void SetHighRoof(int32_t);
	static void SetHighSpeedGasScale(float);
	static void SetGasScaleSpeedThreshold(float);
	static void SetAllowSeatSlide(int32_t);
	static void ClearVehicleSelectInfo(const std::string&, const std::string& = "", const std::string& = "");
	static void AddFlyingActor(const std::string&, const std::string&, const std::string&, const std::string&,
	                           const std::string&);
	static void SetCollisionAttributes(const std::string&, const std::string&, const std::string&, const std::string&);
	static void AddSpawnPoint(const std::string&, const std::string&, const std::string&, const std::string&,
	                          const std::string&, const std::string&, const std::string&, const std::string&);
	static void GagSetWeight(const std::string&);
	static void GagSetLoadDistances(const std::string&, const std::string&);
	static void SetTotalWasps(const std::string&, const std::string&);
	static void AddGlobalProp(const std::string&);
	static void EnableHitAndRun(const std::string& = "");
	static void SetHitAndRunMeter(const std::string&);
	static void SetChaseSpawnRate(const std::string&, const std::string&);
	static void KillAllChaseAI(const std::string&);
	static void ResetHitAndRun(const std::string& = "");
	static void SetHitAndRunDecayInterior(const std::string&);
	static void SetMissionNameIndex(const std::string&);
	static void AddBonusObjective(const std::string&, const std::string& = "");
	static void AttachStatePropCollectible(const std::string&, const std::string&);
	static void MoveStageVehicle(const std::string&, const std::string&, const std::string&);
	static void SetStageCamera(const std::string&, const std::string&, const std::string&);
	static void SetBonusMissionStart(const std::string& = "");
	static void PlacePlayerAtLocatorName(const std::string&);
	static void msPlacePlayerCarAtLocatorName(const std::string&);
	static void ClearTrafficForStage(const std::string& = "");
	static void SetStageAIEvadeCatchupParams(const std::string&, const std::string&, const std::string&);
	static void AllowUserDump(const std::string& = "");
	static void SetVehicleToLoad(const std::string&, const std::string&, const std::string&);
	static void SetConversationCamName(const std::string&);
	static void SetConversationCamPcName(const std::string&);
	static void SetConversationCamNpcName(const std::string&);
	static void SetConversationCamDistance(const std::string&, const std::string&);
	static void CharacterIsChild(const std::string&);
	static void SetCarStartCamera(const std::string&);
	static void SetPlayerCarName(const std::string&, const std::string&);
	static void SetRespawnRate(const std::string&, const std::string&);
	static void ActivateTrigger(const std::string&);
	static void DeactivateTrigger(const std::string&);
	static void CreateAnimPhysObject(const std::string&, const std::string&);
	static void CreateActionEventTrigger(const std::string&, const std::string&, const std::string&, const std::string&,
	                                     const std::string&);
	static void LinkActionToObjectJoint(const std::string&, const std::string&, const std::string&, const std::string&,
	                                    const std::string&);
	static void LinkActionToObject(const std::string&, const std::string&, const std::string&, const std::string&,
	                               const std::string&);
	static void SetCharacterPosition(const std::string&, const std::string&, const std::string&);
	static void ResetCharacter(const std::string&, const std::string&);
};
} // namespace Donut
